<a href="https://colab.research.google.com/github/hwayoungc24-rgb/younghwa/blob/main/spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
docs = [ 'additional income',
'best price',
'big bucks',
'cash bonus',
'earn extra cash',
'spring savings certificate',
'valero gas marketing',
'all domestic employees',
'nominations for oct',
'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [10]:
vocab_size = 50
max_length = 4

encoded_docs = [one_hot(d, vocab_size) for d in docs]
# 훈련 데이터 전용 패딩 변수 생성
train_padded = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

In [4]:
max_length = 4
paddded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(paddded_docs)

[[39 23  0  0]
 [49 32  0  0]
 [13 33  0  0]
 [40  1  0  0]
 [ 1 41 40  0]
 [34 20 16  0]
 [13 15 30  0]
 [39 46 19  0]
 [42  2 31  0]
 [11 32  6  0]]


In [11]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 훈련용 패딩 변수를 넣어 학습 진행
model.fit(train_padded, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(train_padded, labels, verbose=0)
print('Accuracy: %f' % (accuracy * 100))

Accuracy: 100.000000


In [12]:
test_doc = ['big income']
test_encoded = [one_hot(d, vocab_size) for d in test_doc]
test_padded = pad_sequences(test_encoded, maxlen=max_length, padding='post')

# 예측 결과 출력
pred = model.predict(test_padded)
print("스팸 메일일 확률:", pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
스팸 메일일 확률: [[0.5553651]]
